### PR TITLE
Update khalti SDK to make use of updated APIs

### PR DESCRIPTION
**Pull request by Biplab-Dutta**
This PR makes changes in how merchants can use Khalti SDK to make payments.
- Previously, the SDK provided most of the UI elements that should have been incorporated in merchant's app. This change brings a WebView implementation of Khalti Payment Portal for seamless adaptation and payment making process.
- The SDK removes all the deprecated backend APIs with the new APIs.
- Removal of `khalti` package. Now there are only `khalti_core` and `khalti_flutter` packages in this repo.
- Version bump in `khalti_flutter` (v3.1.0) and `khalti_core` (v1.2.0) library.

### CODE REVIEW

**Comment by Ishwor-Shrestha** [comment]
@Biplab-Dutta What are the changes introduced in this PR?

**Comment by Biplab-Dutta** [comment]
> @Biplab-Dutta What are the changes introduced in this PR?

@Ishwor-Shrestha Updated description

**Review by acpmasquerade — CHANGES_REQUESTED** [review]
Dart Package for new version
- khalti_checkout

Flutter package for new version
- khalti_checkout_flutter

Project namespace to be renamed as - "Khalti Checkout"
- and first version to be pushed as 
**1.0.0-preview-release**

**Comment by Biplab-Dutta** [comment]
> Dart Package for new version
> - khalti_checkout
> 
> Flutter package for new version
> - khalti_checkout_flutter
> 
> Project namespace to be renamed as - "Khalti Checkout"
> - and first version to be pushed as 
> **1.0.0-preview-release**

The changes have been made. The release on pub.dev remains. @acpmasquerade

**Pull request closed without merging**
